- examples/existing_resource_group/README.md
- examples/new_resource_group/README.md
This PR includes some example fixes
> fix: Fix examples issues

- README.md
- examples/existing_resource_group/README.md
- examples/existing_resource_group/main.tf
- examples/new_resource_group/README.md
- examples/new_resource_group/main.tf
- main.tf
- modules/infrastructure/eventhub/README.md
- modules/services/cloud-connector/README.md
- modules/services/cloud-connector/main.tf
- modules/services/cloud-connector/variables.tf
- variables.tf
This PR includes:
chore: Improve modules README files.
feat: Add subscription ID within cloud connector config file
> feat: Add subscription ID to cloud connector config file

- examples-internal/existing_resource_group/README.md
- examples-internal/existing_resource_group/main.tf
- examples-internal/existing_resource_group/variables.tf
- examples-internal/existing_resource_group/versions.tf
This PR is about moving existing resource group example to examples-internal folder
> chore: Move existing resource group to examples-internal folder

- examples/single-account/README.md
- examples/single-account/main.tf
- examples/single-account/variables.tf
Name prefix was hardcoded this change sets a name prefix variable with default value.
> fix: Change eventhub module input name prefix

- examples/single-account/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/eventhub/main.tf
- modules/infrastructure/eventhub/variables.tf
This PR remove Active Directory diagnostic setting from infrastructure module.
> chore: Remove unused resource

- examples-internal/existing-resource-group/main.tf
- examples/single-account-k8s/main.tf
- examples/single-account/README.md
- examples/single-account/main.tf
- examples/single-account/variables.tf
- examples/tenant/README.md
- examples/tenant/main.tf
- examples/tenant/variables.tf
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/eventhub/main.tf
- modules/infrastructure/eventhub/variables.tf
- modules/infrastructure/eventhub/versions.tf
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
- modules/services/cloud-connector/main.tf
- modules/services/cloud-connector/variables.tf
- modules/services/cloud-connector/versions.tf
- test/fixtures/single-account/main.tf
Allows to deploy multiple ingestors for the cloud-connector to retrieve events from multiple subscriptions of the same tenant.
> feat: Allow threat detection for multiple subscriptions

- README.md
- examples/single-subscription-k8s/README.md
- examples/single-subscription-k8s/cloudbench.tf
- examples/single-subscription-k8s/variables.tf
- examples/single-subscription/README.md
- examples/single-subscription/cloudbench.tf
- examples/single-subscription/main.tf
- examples/single-subscription/variables.tf
- examples/tenant/README.md
- test/fixtures/single-subscription-k8s/main.tf
- test/fixtures/single-subscription/main.tf
> feat: enable benchmark on single-subscription-k8s

- .github/workflows/ci-integration-test.yaml
- examples/single-subscription-k8s/README.md
- examples/single-subscription-k8s/cloud-connector.tf
- examples/single-subscription-k8s/main.tf
- examples/single-subscription/README.md
- examples/single-subscription/main.tf
- examples/tenant/README.md
- examples/tenant/main.tf
- modules/infrastructure/enterprise_app/main.tf
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/eventhub/main.tf
- modules/infrastructure/eventhub/outputs.tf
- modules/infrastructure/eventhub/variables.tf
- modules/infrastructure/resource_group/README.md
- modules/infrastructure/resource_group/main.tf
- modules/infrastructure/resource_group/outputs.tf
- modules/infrastructure/resource_group/variables.tf
- modules/infrastructure/resource_group/versions.tf
- test/fixtures/single-subscription-k8s/main.tf
- test/fixtures/single-subscription-k8s/variables.tf
- test/fixtures/single-subscription/backend.tf
This PR re enable the kitchen test suite after fixing the problem with the azure service principal permissions. It also extract resource group module from event hub module.
> fix: re enable kitchen test suite

- examples/single-subscription-k8s/README.md
> docs: update single subscription k8s source reference

- examples/single-subscription-k8s/README.md
- examples/single-subscription-k8s/variables.tf
- examples/single-subscription/README.md
- examples/single-subscription/variables.tf
- examples/tenant-subscriptions/README.md
- examples/tenant-subscriptions/variables.tf
- test/fixtures/single-subscription-k8s/main.tf
> feat: Enable cloud benchmarks by default on Azure

- examples/single-subscription-k8s/README.md
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions-k8s/cloud-connector.tf
- examples/tenant-subscriptions-k8s/cloudbench.tf
- examples/tenant-subscriptions-k8s/data.tf
- examples/tenant-subscriptions-k8s/main.tf
- examples/tenant-subscriptions-k8s/variables.tf
- examples/tenant-subscriptions-k8s/versions.tf
This PR includes a new use example: tenant subscriptions k8s
> chore: Add tenant subscriptions k8s example

- examples/single-subscription/README.md
- examples/single-subscription/main.tf
- examples/single-subscription/variables.tf
- examples/tenant-subscriptions/README.md
- examples/tenant-subscriptions/main.tf
- examples/tenant-subscriptions/variables.tf
- modules/services/cloud-connector/README.md
- modules/services/cloud-connector/main.tf
- modules/services/cloud-connector/variables.tf
Azure container group accepts cpu and memory as parameters
> feat: cpu and memory as parameters

- examples/trigger-events/README.md
Rename AWS to Azure in RREADME
> chore: Update README.md

- README.md
- examples/single-subscription-k8s/README.md
- examples/single-subscription/README.md
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions/README.md
- examples/trigger-events/README.md
- modules/infrastructure/container_registry/README.md
- modules/infrastructure/enterprise_app/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/resource_group/README.md
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
> doc: clarify module features

- .pre-commit-config.yaml
- examples/single-subscription-k8s/README.md
- examples/single-subscription/README.md
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions/README.md
- examples/trigger-events/README.md
- modules/infrastructure/container_registry/README.md
- modules/infrastructure/enterprise_app/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/resource_group/README.md
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
> chore: tflint upgrade

- README.md
> doc: add-questionnaire

- examples/single-subscription-k8s/README.md
- examples/single-subscription-k8s/main.tf
- examples/single-subscription-k8s/provider.tf
- examples/single-subscription-k8s/variables.tf
- examples/single-subscription/README.md
- examples/single-subscription/cloud-connector.tf
- examples/single-subscription/provider.tf
- examples/single-subscription/scanning.tf
- examples/single-subscription/variables.tf
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions-k8s/main.tf
- examples/tenant-subscriptions-k8s/variables.tf
- examples/tenant-subscriptions/README.md
- examples/tenant-subscriptions/scanning.tf
- examples/tenant-subscriptions/variables.tf
- examples/trigger-events/README.md
- modules/infrastructure/container_registry/README.md
- modules/infrastructure/container_registry/main.tf
- modules/infrastructure/container_registry/outputs.tf
- modules/infrastructure/container_registry/variables.tf
- modules/infrastructure/enterprise_app/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/resource_group/README.md
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
> feat: allow multiple registry for scanning

- examples/single-subscription-k8s/README.md
- examples/single-subscription/README.md
- examples/single-subscription/variables.tf
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions/README.md
- examples/trigger-events/README.md
- modules/infrastructure/container_registry/README.md
- modules/infrastructure/enterprise_app/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/resource_group/README.md
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
> fix: default to disable again scanning

- examples/single-subscription-k8s/README.md
- examples/single-subscription/README.md
- examples/tenant-subscriptions-k8s/README.md
- examples/tenant-subscriptions/README.md
- examples/trigger-events/README.md
- modules/infrastructure/container_registry/README.md
- modules/infrastructure/enterprise_app/README.md
- modules/infrastructure/eventhub/README.md
- modules/infrastructure/eventhub/main.tf
- modules/infrastructure/resource_group/README.md
- modules/services/cloud-bench/trust_relationship/README.md
- modules/services/cloud-connector/README.md
- modules/services/cloud-connector/main.tf
This PR includes the terraform resources update, some of them were outdated.
> fix: update terraform resources

- CODEOWNERS
> Add onboarding team as codeowners

- README.md
> docs: update role/permission requirement
